"""
Water supplies data for all parishes
"""

def get_all_supplies():
    """Returns all water supplies with parish information"""
    return [
        # Westmoreland Supplies
        # Treated Supplies
        ('Roaring River 1', 'treated', 'NWC', 'Savanna-la-Mar', 'Westmoreland'),
        ('Roaring River 2', 'treated', 'NWC', 'Savanna-la-Mar', 'Westmoreland'),
        ('Bulstrode', 'treated', 'NWC', 'Bulstrode', 'Westmoreland'),
        ('Dantrout', 'treated', 'NWC', 'Dantrout', 'Westmoreland'),
        ('Bluefield\'s', 'treated', 'NWC', 'Bluefields', 'Westmoreland'),
        ('Negril/Logwood', 'treated', 'NWC', 'Negril', 'Westmoreland'),
        ('Bethel Town/Cambridge', 'treated', 'NWC', 'Bethel Town', 'Westmoreland'),
        ('Venture-Williamsfield', 'treated', 'NWC', 'Venture', 'Westmoreland'),
        ('Shettlewood', 'treated', 'NWC', 'Shettlewood', 'Westmoreland'),
        ('Cave', 'treated', 'NWC', 'Cave', 'Westmoreland'),
        ('Carawina', 'treated', 'NWC', 'Carawina', 'Westmoreland'),
        ('Dean\'s Valley', 'treated', 'NWC', 'Dean\'s Valley', 'Westmoreland'),
        ('New Works', 'treated', 'PC', 'New Works', 'Westmoreland'),
        ('New Works-Steward Lands', 'treated', 'PC', 'New Works', 'Westmoreland'),
        ('Castle Mountain', 'treated', 'PC', 'Castle Mountain', 'Westmoreland'),
        ('Berkshire', 'treated', 'PC', 'Berkshire', 'Westmoreland'),
        ('Amity Mountains', 'treated', 'PC', 'Amity', 'Westmoreland'),
        ('Beeston Spring', 'treated', 'PC', 'Beeston Spring', 'Westmoreland'),
        ('Spring Gardens', 'treated', 'Private', 'Spring Gardens', 'Westmoreland'),

        # Untreated Supplies
        ('Content', 'untreated', 'PC', 'Content', 'Westmoreland'),
        ('Holly Hill', 'untreated', 'PC', 'Holly Hill', 'Westmoreland'),
        ('Bunion (Bunyan)', 'untreated', 'PC', 'Bunion', 'Westmoreland'),
        ('Lundi', 'untreated', 'PC', 'Lundi', 'Westmoreland'),
        ('Pinnock Shafton', 'untreated', 'PC', 'Pinnock', 'Westmoreland'),
        ('Orange Hill', 'untreated', 'PC', 'Orange Hill', 'Westmoreland'),
        ('Cair Curran Cedar Valley', 'untreated', 'PC', 'Cedar Valley', 'Westmoreland'),
        ('Leamington', 'untreated', 'PC', 'Leamington', 'Westmoreland'),
        ('Charlie Mount', 'untreated', 'PC', 'Charlie Mount', 'Westmoreland'),
        ('New Roads', 'untreated', 'PC', 'New Roads', 'Westmoreland'),
        ('Belvedere', 'untreated', 'PC', 'Belvedere', 'Westmoreland'),
        ('York Mountain', 'untreated', 'PC', 'York Mountain', 'Westmoreland'),
        ('Ashton', 'untreated', 'PC', 'Ashton', 'Westmoreland'),
        ('Kilmarnock', 'untreated', 'PC', 'Kilmarnock', 'Westmoreland'),
        ('Bronti', 'untreated', 'PC', 'Bronti', 'Westmoreland'),
        ('Argyle Mountain', 'untreated', 'PC', 'Argyle', 'Westmoreland'),
        ('Bog', 'untreated', 'PC', 'Bog', 'Westmoreland'),
        ('Porters Mountain', 'untreated', 'PC', 'Porters Mountain', 'Westmoreland'),
        ('Ketto', 'untreated', 'Private', 'Ketto', 'Westmoreland'),
        ('Lambs River', 'untreated', 'PC', 'Lambs River', 'Westmoreland'),
        ('Bath Mtns.', 'untreated', 'PC', 'Bath Mountains', 'Westmoreland'),

        # Trelawny Supplies
        # Add Trelawny water supplies here
        ('Rio Bueno', 'treated', 'NWC', 'Rio Bueno', 'Trelawny'),
        ('Duncans', 'treated', 'NWC', 'Duncans', 'Trelawny'),
        ('Falmouth', 'treated', 'NWC', 'Falmouth', 'Trelawny'),
        ('Martha Brae', 'untreated', 'PC', 'Martha Brae', 'Trelawny'),
        ('Clarks Town', 'untreated', 'PC', 'Clarks Town', 'Trelawny'),
        ('Wait-a-Bit', 'untreated', 'PC', 'Wait-a-Bit', 'Trelawny'),

        # Hanover Supplies
        # HMC Supplies (34 - All Untreated)
        ('Claremont Catchment', 'untreated', 'HMC', 'Claremont', 'Hanover'),
        ('Thompson Hill Catchment', 'untreated', 'HMC', 'Thompson Hill', 'Hanover'),
        ('Upper Rock Spring', 'untreated', 'HMC', 'Upper Rock Spring', 'Hanover'),
        ('Success Catchment', 'untreated', 'HMC', 'Success', 'Hanover'),
        ('Bamboo Spring', 'untreated', 'HMC', 'Bomboo', 'Hanover'),
        ('Jericho Spring', 'untreated', 'HMC', 'Jericho', 'Hanover'),
        ('Lethe Spring', 'untreated', 'HMC', 'Lethe', 'Hanover'),
        ('Welcome Spring', 'untreated', 'HMC', 'Welcome', 'Hanover'),
        ('Knockalva Catchment', 'untreated', 'HMC', 'Knocklava', 'Hanover'),
        ('Flamstead Spring', 'untreated', 'HMC', 'Flamstead', 'Hanover'),
        ('Pierces Village Catchment', 'untreated', 'HMC', 'Pierces Village', 'Hanover'),
        ('Cold Spring', 'untreated', 'HMC', 'Cold Spring', 'Hanover'),
        ('Rejion Tank', 'untreated', 'HMC', 'Rejoin', 'Hanover'),
        ('Rejoin Catchment', 'untreated', 'HMC', 'Rejoin', 'Hanover'),
        ('Chovey Hole', 'untreated', 'HMC', 'Askenish', 'Hanover'),
        ('Content Catchment', 'untreated', 'HMC', 'Content', 'Hanover'),
        ('St Simon Spring', 'untreated', 'HMC', 'St. Simon', 'Hanover'),
        ('Donalva Spring', 'untreated', 'HMC', 'Maryland', 'Hanover'),
        ('Sawpit Spring', 'untreated', 'HMC', 'Cove Road', 'Hanover'),
        ('Patty Hill Spring', 'untreated', 'HMC', 'Patty Hill', 'Hanover'),
        ('Woodsville Catchment', 'untreated', 'HMC', 'Woodsville', 'Hanover'),
        ('Dias Tank', 'untreated', 'HMC', 'Dias', 'Hanover'),
        ('Anderson Spring', 'untreated', 'HMC', 'Sandy Bay', 'Hanover'),
        ('Bamboo Roadside Overflow', 'untreated', 'HMC', 'Bamboo', 'Hanover'),
        ('Axe-and-Adze Catchment', 'untreated', 'HMC', 'Axe-And-Adze', 'Hanover'),
        ('Soja Spring', 'untreated', 'HMC', 'Retrieve', 'Hanover'),
        ('Castle Hyde Catchment', 'untreated', 'HMC', 'Castle Hyde', 'Hanover'),
        ('Medley Spring', 'untreated', 'HMC', 'Medley', 'Hanover'),
        ('Craig Nathan', 'untreated', 'HMC', 'Askenish', 'Hanover'),
        ('Jabez Catchment', 'untreated', 'HMC', 'Retieve', 'Hanover'),
        ('Rockfoot Reservoir', 'untreated', 'HMC', 'Askenish', 'Hanover'),
        ('Burntside Spring', 'untreated', 'HMC', 'Maryland', 'Hanover'),
        ('Old Cold Spring', 'untreated', 'HMC', 'Cold Spring', 'Hanover'),
        ('Spring Georgia', 'untreated', 'HMC', 'Georgia', 'Hanover'),

        # NWC Supplies (5 - All Treated)
        ('Logwood', 'treated', 'NWC', 'Logwood', 'Hanover'),
        ('New Milns', 'treated', 'NWC', 'New Milns', 'Hanover'),
        ('Kendal', 'treated', 'NWC', 'Kendal', 'Hanover'),
        ('Shettlewood Hanover', 'treated', 'NWC', 'Ramble', 'Hanover'),
        ('Great River - St. James', 'treated', 'NWC', 'St. James', 'Hanover'),

        # Private Supplies (18 - 16 Treated, 2 Untreated)
        ('Tryall Club', 'treated', 'Private', 'Sandy Bay', 'Hanover'),
        ('Vivid Water Store', 'treated', 'Private', 'Hopewell', 'Hanover'),
        ('Aquacity Water Store', 'treated', 'Private', 'Hopewell', 'Hanover'),
        ('M&B Water Store', 'treated', 'Private', 'Hopewell', 'Hanover'),
        ('Quenched Water Store', 'treated', 'Private', 'Lucea', 'Hanover'),
        ('Epic Blue', 'treated', 'Private', 'Lucea', 'Hanover'),
        ('Dynasty Water Store', 'treated', 'Private', 'Orange Bay', 'Hanover'),
        ('Valley Dew', 'untreated', 'Private', 'Miles Town, Ramble', 'Hanover'),
        ('Jus Chill', 'untreated', 'Private', 'Lethe', 'Hanover'),
        ('Royalton Resorts', 'treated', 'Private', 'Negril', 'Hanover'),
        ('Sandals Negril', 'treated', 'Private', 'Negril', 'Hanover'),
        ('Couples Negril', 'treated', 'Private', 'Negril', 'Hanover'),
        ('Sunset At The Palms', 'treated', 'Private', 'Negril', 'Hanover'),
        ('Azul Resort', 'treated', 'Private', 'Negril', 'Hanover'),
        ('Round Hill Resort', 'treated', 'Private', 'John Pringle drive, Hopewell', 'Hanover'),
        ('Hedonism II', 'treated', 'Private', 'Negril', 'Hanover'),
        ('Riu Tropical Bay', 'treated', 'Private', 'Negril', 'Hanover'),
        ('Riu Jamiecotel', 'treated', 'Private', 'Negril', 'Hanover'),
    ]